from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index_page, name='index'), url(r'^register/login/$', views.login_page, name='login'),
    url(r'^software/$', views.software_page, name='software'),
    url(r'^register/create/$', views.create_new_user_page, name='CreateNewUser'),
    url(r'^register/creating/$', views.creating_new_user, name='CreatingNewUser'),
    url(r'^register/logining/$', views.logining, name='logining'),
    url(r'^logout/$', views.loging_out, name='logout'),
    url(r'^tutorial/(?P<tutorialid>[0-9]+)/$', views.tutorial_page, name='tutorial'),
    url(r'^ccc/$', views.ccc, name='ccc'),
    url(r'^blogs/(?P<page_num>[0-9]+)/$', views.blog_list, name='BlogList'),
    url(r'^blog/(?P<blog_id>[0-9]+)/$', views.blog_detail, name='BlogDetail'),
    url(r'^ajax_test/$', views.test_ajax, name='test_ajax'),
    url(r'^param_test/(?P<param>[0-9]+)/$', views.test_param, name='test_param'),
    url(r'^gv/$', views.get_video_url, name='getVideoUrl'),
    url(r'^checkSms/$', views.check_sms, name='checkSms'),
    url(r'^checkMobileExists/$', views.check_mobile_exists, name='checkeMobileExits'),
    url(r'^sendsms/$', views.send_sms, name='sendSms'),
    url(r'^classeslist/(?P<ins_id>[0-9]+)/(?P<page_num>[0-9]+)/$', views.classes_list, name='classesList'),
    url(r'^Tutoriallist/(?P<category_id>[0-9]+)/$', views.tutorial_list_page, name='tutorialList'),
    url(r'^classesfilter/(?P<ins_id>[0-9]+)/(?P<cat_id>[0-9]+)/(?P<page_num>[0-9]+)/$', views.classes_filter,
        name='classesFilter'),
    url(r'^shop/$', views.shop, name='shop'),
    # url(r'^x_shop_s/$', views.shop_s, name='shop_s'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/changing/$', views.changing_password, name='changingPassword'),
    url(r'^buy/(?P<c_id>[0-9]+)/$', views.buy, name='buy'),
    url(r'^pay/(?P<c_id>[0-9]+)/$', views.pay, name='pay'),
    url(r'^downloads/$', views.downloads, name='downloads'),
    url(r'^payreturn/$', views.alipay_return_url, name='alipay_return'),
    url(r'^paynotify/$', views.alipay_notify_url, name='alipay_notify'),
    url(r'^forget/$', views.forget_password_page, name='forget_password'),
    url(r'^reset/$', views.reset_password, name='reset_password'),
    url(r'^getnow/$', views.get_now, name='get_now'),
    url(r'^kota/', views.kota, name='kota'),
    url(r'^deluser/(?P<uname>[0-9]+)/$', views.delete_user, name='delete_user')
]
